baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Cornerstone Pays MQ CRM"
[[menu.main]]
URL = ""
name = ""
weight = ""
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = ""
name = "Pricing "
weight = "2"
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = "5"
[params]
address = "17822 E. Seventeenth Street Suite 412 Tustin, CA 92780"
author = "Johnathan Smith"
copyright = "Copyrighht &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "This is meta description"
email = "INFO@CSTONEMAIL.COM"
google_analitycs_id = "Your ID"
home = "Home"
logo = "Cornerstone logo 1.17.jpg"
phone = "888-506-0208"
theme_color = "#008cdd"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.instagram.com/cornerstonepays/"
icon = "ti-Instagram"
[[params.social]]
URL = "#https://twitter.com/CornerstonePays"
icon = "ti-twitter"
[[params.social]]
URL = "#"
icon = "ti-instagram"
[[params.social]]
URL = "#"
icon = "ti-dribbble"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
